export const ADMIN_LOGIN_REQUEST = "ADMIN_lOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_lOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_lOGIN_FAIL";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";


export const LIST_USERS_REQUEST = "LIST_USERS_REQUEST";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_FAIL = "LIST_USERS_FAIL";


export const BLOCK_USERS_REQUEST = "BLOCK_USERS_REQUEST";
export const BLOCK_USERS_SUCCESS = "BLOCK_USERS_SUCCESS";
export const BLOCK_USERS_FAIL = "BLOCK_USERS_FAIL";
